version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: equipment_user
      MYSQL_PASSWORD: equipment_user_password
      MYSQL_DATABASE: equipment

  spring-boot-app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/equipment
        SPRING_DATASOURCE_USERNAME: equipment_user
        SPRING_DATASOURCE_PASSWORD: equipment_user_password

  react-app:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:80"
